#! /bin/bash

function bib() {
    if [ -n $BIB ]; then
        echo "BIB env not defined."
        return 1
    fi
    local line filepath basename
    line=$(find "$BIB" -maxdepth 1 -type f -name '*.pdf' \
        | awk -F/ '{print $0 "\t" gensub(/\.pdf$/, "", 1, $NF)}' \
        | sort --reverse -t$'\t' -k2 \
        | fzf --with-nth=2 --delimiter='\t' \
            --preview 'pdftotext {1} - | head -40' --preview-window=right:70%)
    [ -z "$line" ] && return
    filepath="${line%%$'\t'*}"
    basename="${line#*$'\t'}"
    [ -n "$filepath" ] && zathura "$filepath"
}
